baseurl:    /
url:        http://www.hawkeward.com

permalink:  /:categories/:title

markdown:   kramdown
kramdown:
  auto_ids: false

excerpt_separator: <!--more-->

sass:
  sass_dir: scss
  style: :compressed


exclude:    [_psd]