permalink: /:categories/:title/

markdown: kramdown
kramdown:
  auto_ids: false

excerpt_separator: <!--more-->

sass:
  sass_dir: scss
#   style: :compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/work"
      type: "posts"
    values:
      layout: "work"

exclude: [_psd]
